# -*- coding: utf-8 -*-
"""paragliding_battle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h2siYFIGpXax6KXlkZV3rHgZesS_o2Eu

# New Section
"""

import streamlit as st
import random
import time

st.set_page_config(page_title="🪂 Paragliding Survival Battle", layout="centered")

st.title("🏞️ Paragliding Survival Challenge on Mystic Cliffs")

# Editable player names
st.subheader("🌤️ Name Your Gliders")
players = []
for i in range(6):
    name = st.text_input(f"Glider {i+1} Name", value=f"Glider{i+1}")
    players.append(name)

glider_icons = ["🪂", "🦅", "🌬️", "🎯", "🔥", "💨"]

if st.button("🏁 Begin Paragliding Showdown!"):
    st.subheader("🌪️ Gliders in the Air... Survive 30 Seconds!")

    hp = {player: 100 for player in players}
    alive = players.copy()
    progress = {player: st.progress(100) for player in players}
    battle_log = st.empty()

    start_time = time.time()

    while time.time() - start_time < 30 and len(alive) > 1:
        time.sleep(1.5)
        attacker, target = random.sample(alive, 2)
        move = random.choice(["crosswind", "thermal flip", "glide punch", "spiral dive"])
        icon = random.choice(glider_icons)
        damage = random.randint(10, 25)
        hp[target] -= damage

        battle_log.markdown(f"{icon} **{attacker}** used **{move}** on **{target}** causing **{damage}** damage!")

        if hp[target] <= 0:
            hp[target] = 0
            alive.remove(target)
            battle_log.markdown(f"💥 **{target}** crash landed and is out of the race!")

        for p in players:
            progress[p].progress(hp[p])

    if len(alive) == 1:
        winner = alive[0]
        st.success(f"🏆 The last glider soaring is **{winner}**! Victory on the cliffs!")
    else:
        st.warning("⏱️ Time's up! No single winner... it was a tough match!")