# -*- coding: utf-8 -*-
"""scrum_picker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aIXmAWAb_Rmo-IUU1963LpS7LouVk83I
"""

!ngrok config add-authtoken 2xzUqPJTFD1GRcAFtXAzySIYjqh_7VtRcigYUxBkyWSqUwsce
!pip install streamlit pyngrok streamlit-option-menu pygame --quiet

# 🟢 Cell 2: Write app code to a file
app_code = """
import streamlit as st
import random
import time
from streamlit_option_menu import option_menu

st.set_page_config(page_title="Scrum Host Picker", layout="wide")

st.markdown('<h1 style="text-align: center; color: red;">🏹⚔️ Battle Arena For Scrum ⚔️🏹</h1>', unsafe_allow_html=True)

# Sidebar for names
st.sidebar.header("🛡️ Enter Warrior Names")
names = []
for i in range(1, 7):
    name = st.sidebar.text_input(f"Warrior {i}", f"Warrior{i}")
    names.append(name)

# Background and animation display
col1, col2, col3 = st.columns([1,2,1])

with col2:
    if st.button("⚔️ Begin Battle!"):
        st.markdown("## 🕒 The Battle Begins...")
        with st.spinner("Warriors are fighting..."):
            duration = 60  # seconds
            start_time = time.time()
            while time.time() - start_time < duration:
                warrior1, warrior2 = random.sample(names, 2)
                st.image("https://i.imgur.com/6aLz6dl.gif", width=400)
                st.markdown(f"### {warrior1} clashes with {warrior2}!")
                time.sleep(5)
                st.empty()

        winner = random.choice(names)
        st.balloons()
        st.markdown(f"<h2 style='color:green; text-align:center;'>🏆 {winner} will host today's Scrum! 🏆</h2>", unsafe_allow_html=True)
    else:
        st.image("https://i.imgur.com/6aLz6dl.gif", width=500)
        st.markdown("### Click the button above to begin the battle!")
"""

with open("scrum_host_picker.py", "w") as f:
    f.write(app_code)

# 🟢 Cell 3: Launch Streamlit app via ngrok
from pyngrok import ngrok
import os
os.system("pkill streamlit")

# Create tunnel
public_url = ngrok.connect(8501)
print("Streamlit app running at:", public_url)

# Run the app
!streamlit run scrum_host_picker.py &>/dev/null &

!pip install streamlit pyngrok streamlit-option-menu --quiet

# Download a known working cartoon GIF (we'll base64 encode it)
import base64
from urllib.request import urlopen

url = "https://cdn.dribbble.com/users/251076/screenshots/2855546/wonderwoman_new.gif"  # Funny cartoon warrior
gif_data = urlopen(url).read()

with open("warrior.gif", "wb") as f:
    f.write(gif_data)

# Encode as base64 to embed
gif_base64 = base64.b64encode(gif_data).decode("utf-8")

# Save to a .txt file so we can use it in Streamlit app
with open("encoded_gif.txt", "w") as f:
    f.write(gif_base64)

app_code = '''
import streamlit as st
import random
import time

# Load base64 gif
with open("encoded_gif.txt", "r") as f:
    gif_data = f.read()

# Prepare HTML for embedded base64 image
battle_gif_html = f"<img src='data:image/gif;base64,{gif_data}' width='400'/>"

# Set page config
st.set_page_config(page_title="Battle Arena for Scrum Host", layout="centered")

# Header
st.markdown("<h1 style='text-align: center; color: darkred;'>⚔️ Battle Arena for Scrum Host ⚔️</h1>", unsafe_allow_html=True)

# Sidebar input for names
st.sidebar.header("🛡️ Enter Warrior Names")
names = [st.sidebar.text_input(f"Warrior {i+1}", f"Warrior{i+1}") for i in range(6)]

# Placeholder for display
placeholder = st.empty()

if st.button("🔥 Begin Battle!"):
    st.markdown("<h2 style='text-align: center; color: orange;'> Result...</h2>", unsafe_allow_html=True)

    start_time = time.time()
    duration = 15  # seconds

    while time.time() - start_time < duration:
        w1, w2 = random.sample(names, 2)
        with placeholder.container():
            st.markdown("<div style='text-align: center;'>", unsafe_allow_html=True)
            st.markdown(battle_gif_html, unsafe_allow_html=True)
            st.markdown(f"<h3 style='color: navy;'>{w1} ⚔️ vs ⚔️ {w2}</h3>", unsafe_allow_html=True)
            st.markdown("</div>", unsafe_allow_html=True)
        time.sleep(3)

    winner = random.choice(names)
    st.balloons()
    st.markdown(f"<h2 style='text-align: center; color: green;'>🏆 {winner} will host tomorrow's Scrum! 🏆</h2>", unsafe_allow_html=True)

else:
    with placeholder.container():
        st.markdown("<div style='text-align: center;'>", unsafe_allow_html=True)
        st.markdown(battle_gif_html, unsafe_allow_html=True)
        st.markdown("<h4>Click 'Begin Battle!' to start the Scrum host selection.</h4>", unsafe_allow_html=True)
        st.markdown("</div>", unsafe_allow_html=True)
'''

with open("scrum_host_base64.py", "w") as f:
    f.write(app_code)

from pyngrok import ngrok
import os
os.system("pkill streamlit")

public_url = ngrok.connect(8501)
print("✅ Your App is Live at:", public_url)

!streamlit run scrum_host_battle_final.py &>/dev/null &

!pkill streamlit
!pkill -f ngrok