# -*- coding: utf-8 -*-
"""SWIM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h2siYFIGpXax6KXlkZV3rHgZesS_o2Eu

# New Section
"""

import streamlit as st
import random
import time

st.set_page_config(page_title="🏊 6-Player Swimming Race", layout="centered")

st.title("🏁 6-Player Swimming Race")

# Player name inputs
st.subheader("🔧 Edit Swimmer Names")
players = []
for i in range(6):
    name = st.text_input(f"Swimmer {i+1} Name", value=f"Swimmer{i+1}")
    players.append(name)

if st.button("🌊 Start Race"):
    st.subheader("🚦 Race in Progress...")

    st.write("Each swimmer swims at random speeds. Whoever reaches 100 meters first wins!")
    progress_bars = {player: st.progress(0) for player in players}
    distances = {player: 0 for player in players}
    winner_declared = False

    while not winner_declared:
        for player in players:
            speed = random.randint(5, 15)  # meters per update
            distances[player] += speed
            percent = min(100, int(distances[player]))
            progress_bars[player].progress(percent)

            if distances[player] >= 100 and not winner_declared:
                st.success(f"🏆 Winner: **{player}** reached 100 meters!")
                winner_declared = True
                break

        time.sleep(0.5)